### PR TITLE
feat: capture remaining params

### PR DESCRIPTION
**Pull request by anuragsoni**
Potential fix for #51

### CODE REVIEW

**Comment by anuragsoni** [comment]
@sazarkin This could be one possible way to get a capture_all functionality. I'm still on the fence for the best way here. I don't really like that we silently have routes that overlap so if i add the following routes:

```
1. users <$> s "user" *> str </> capture_all
2. users <$> s "user" *> int </> ...
```
Route 2 will never match, and there is no feedback about that.

**Comment by anuragsoni** [comment]
@ulrikstrid was interested in something similar too

**Comment by Lupus** [comment]
> Route 2 will never match, and there is no feedback about that.

Right now we have to solve that with default handler splitting the path manually and pattern matching routes that need to capture large paths of urls. I believe `capture_all` would be a better approach. In which version did it get included @anuragsoni ?

**Comment by anuragsoni** [comment]
> In which version did it get included

This wasn't implemented yet. The approach in this PR doesn't work for printing routes, and whatever approach we go with should work with the `sprintf` style route printing. Having a capture_all style option will indeed be nice and i think it should be easy enough at-least for the parsing piece (and now we have a nice way to ensure that a user can't mis-use the capture_all by trying to add it anywhere except the end of route). Maybe limiting the capture_all to returning a `string list` will be good enough?

I think it's fine to add it in with documentation indicating the caveats that route ordering is important when using capture_all. I'll take another look at this soon after this week as this week's a little busy for me.

**Comment by Lupus** [comment]
Thanks for heads up! No rush, we already have something that works :) Just figuring out what will be the long term plan.

**Pull request closed without merging**
