### PR TITLE
Add bucklescript support

### PR DESCRIPTION
**Pull request by Risto-Stevcev**

### CODE REVIEW

**Comment by anuragsoni** [comment]
Thank you! Is there a recommended CI setup for bucklescript projects? I'm guessing the github-actions for node should be a good starting point.

On a related note what's the recommended publishing workflow for bucklescript libraries?

**Comment by Risto-Stevcev** [comment]
You can just use the default node build for travis, see the [travis example here][1] on bs-webapi-incubator, which is a popular official reasonml lib that provides bindings to web apis.

The reason it works is because the travis build by convention will check the `package.json` and build (and test) with the default `build` and `test` commands:
https://github.com/reasonml-community/bs-webapi-incubator/blob/master/package.json#L17-L22

[1]: https://github.com/reasonml-community/bs-webapi-incubator/blob/master/.travis.yml

**Comment by anuragsoni** [comment]
> You can just use the default node build for travis, see the [travis example here](https://github.com/reasonml-community/bs-webapi-incubator/blob/master/.travis.yml) on bs-webapi-incubator, which is a popular official reasonml lib that provides bindings to web apis.

Perfect! Thanks again for the patch. I'll add the CI setup and merge this later tonight. I can work on getting this on npm/github npm registry after that.

**Comment by anuragsoni** [comment]
This was added as part of #104

**Pull request closed without merging**
